name: Build Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: ./server

      - name: Install server dependencies
        run: npm install --prefix server

      - name: Run tests
        run: |
          if [ -f "package.json" ]; then
              if grep -q '"test":' package.json; then
                  npm test
              fi
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            server
            *
            .*